name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Frontend Setup
        working-directory: ./frontend
        run: |
          npm install

      
      - name: Backend Setup
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/backend-app:latest ./backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/frontend-app:latest ./frontend

      
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/backend-app:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/frontend-app:latest

      - name : security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USER }}/backend-app:latest
       # ðŸŸ¦ Install Kubectl
      - name: Install kubectl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y kubectl

      # ðŸŸ© Install Minikube
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/

      # ðŸŸ¨ Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          kubectl get nodes

      # ðŸŸ§ Apply Kubernetes manifests
      - name: Deploy Backend & Frontend
        run: |
          kubectl apply -f backend-k8s/backend-deployment.yaml
          kubectl apply -f backend-k8s/backend-service.yaml
          kubectl apply -f backend-k8s/frontend-deployment.yaml
          kubectl apply -f backend-k8s/frontend-service.yaml
          kubectl get all

      # ðŸŸª Verify Deployment
      - name: Verify Services
        run: |
          kubectl get svc