name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Frontend Setup
        working-directory: ./frontend
        run: |
          npm install

      
      - name: Backend Setup
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/backend-app:latest ./backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/frontend-app:latest ./frontend

      
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/backend-app:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/frontend-app:latest

      - name : security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USER }}/backend-app:latest

      - name: Install dependencies for Minikube
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack socat ebtables curl
          CRICTL_VERSION="v1.29.0"
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
          sudo tar zxvf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz -C /usr/local/bin
          rm -f crictl-${CRICTL_VERSION}-linux-amd64.tar.gz

      # ‚öôÔ∏è Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none --force
          sudo chmod -R a+r ~/.kube ~/.minikube
          kubectl cluster-info
          kubectl get nodes

      # üöÄ Deploy to Kubernetes
      - name: Deploy to Minikube
        run: |
          kubectl apply -f backend-k8s/backend-deployment.yaml
          kubectl apply -f backend-k8s/backend-service.yaml
          kubectl apply -f backend-k8s/frontend-deployment.yaml
          kubectl apply -f backend-k8s/frontend-service.yaml
          kubectl get pods -A

      # üü™ Verify Deployment
      - name: Verify Services
        run: |
          kubectl get svc